In [1]:
import requests

headers = {
    'Authorization': 'Token e4342ac4fcf98c2e1910b122cb4103c059f8bbfc',
}

response = requests.get('https://bilishorturl.ml/api/projects/3/export?exportType=JSON', headers=headers)

import json
annotations = json.loads(response.content)
device = 'cuda'

In [2]:
import os
import torch
import numpy as np

keypoints_mapping = {}

x_grid_size = 20
y_grid_size = 35
grid_num = x_grid_size * y_grid_size

unknown_idx = 0


def getCenter(keypoints):
    for point in keypoints:
        point['center_x'] = point['x'] + point['width'] / 2 
        point['center_y'] = point['y'] + point['height'] / 2

# return_interpolation: When true append whether interpolated at the end
# 1 means exist, 0 means missing
def interpolation(keypoints, frames):
    prev = keypoints[0]['frame'] - 1
    prev_x = 0
    prev_y = 0
    res = np.zeros((frames,1))
    for i in keypoints:
        diff = i['frame'] - prev
        cur_x = i['center_x']
        cur_y = i['center_y']
        cur = i['frame']
        for j in range(prev + 1, i['frame']):
            # tmp = {'frame': j}
            tmp_x = (prev_x * (cur - j) + cur_x * (j - prev)) / diff
            tmp_y = (prev_y * (cur - j) + cur_y * (j - prev)) / diff

            res[j - 1, 0] = min(int(tmp_x / 100 * x_grid_size) * y_grid_size + int(tmp_y / 100 * y_grid_size) + 1, grid_num)
            # if return_interpolation:
            #     res[j - 1, -1] = 1
            # tmp['interpolated'] = True
            # res.append(tmp)
        res[cur - 1, 0] = min(int(cur_x / 100 * x_grid_size) * y_grid_size + int(cur_y / 100 * y_grid_size) + 1, grid_num)
        # if return_interpolation:
        #     res[cur - 1, -1] = 1
        prev_x = cur_x
        prev_y = cur_y
        prev = i['frame']

    return res

def process_seq(boxes):
    wand_end_keypoint = None
    wand_tip_keypoint = None
    wand_end_framesCount = None
    wand_tip_framesCount = None

    for i in boxes:
        if 'labels' not in i['value'].keys():
            continue
        if i['value']['labels'][0] == labels_name[0]:
            wand_tip_keypoint = i['value']['sequence']
            wand_tip_framesCount = i['value']['framesCount']
        elif i['value']['labels'][0] == labels_name[1]:
            wand_end_keypoint = i['value']['sequence']
            wand_end_framesCount = i['value']['framesCount']
    
    assert wand_tip_keypoint and wand_end_keypoint, f"missing annotations for {annotation['id']}"
    assert wand_end_framesCount == wand_tip_framesCount, f'frames not matched for {annotation["id"]}'

    framesCount = wand_end_framesCount
    # assert boxes[0]['value']['framesCount'] == boxes[1]['value']['framesCount'], f'frames not matched for {annotation["id"]}'
    # assert len(boxes) >= 2, f"missing annotations for {annotation['id']}"

    
    getCenter(wand_end_keypoint)

    wand_end_keypoint = interpolation(wand_end_keypoint, framesCount)


    getCenter(wand_tip_keypoint)

    wand_tip_keypoint = interpolation(wand_tip_keypoint, framesCount)


    return framesCount, wand_end_keypoint, wand_tip_keypoint


labels_name = ['wand tip', 'wand end']

for annotation in annotations:
    vid_name = annotation['file_upload']

    # boxes = annotation['annotations'][0]['result']
    
    framesCount, wand_end_keypoint, wand_tip_keypoint = process_seq(annotation['annotations'][0]['result'])

    concat_keypoint = np.zeros(shape=(framesCount, 2))
    concat_keypoint[:, :1] = wand_end_keypoint
    concat_keypoint[:, 1:] = wand_tip_keypoint

    
    keypoints_mapping[vid_name] = torch.tensor(concat_keypoint)
    


c:\Users\29197\miniconda3\envs\566_new\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
response = requests.get(f'https://bilishorturl.ml/api/projects/3/tasks/?page_size=-1', headers=headers)

all_tasks = json.loads(response.content)


In [4]:
response = requests.get(f'https://bilishorturl.ml/api/predictions', headers=headers)

assert response.status_code == 200, "connection error"

all_predictions = json.loads(response.content)

In [5]:
all_predictions[1].keys()

dict_keys(['id', 'model_version', 'created_ago', 'result', 'score', 'cluster', 'neighbors', 'mislabeling', 'created_at', 'updated_at', 'task'])

In [6]:
# the directory that contains original videos

import os
source_dir = "G:/.shortcut-targets-by-id/1eyTB0qCfXgrxNsrmWNeLNbd5sTKzP5HT/Data Wizards/dataset/processed_vid"
category_mapping = {"3-24 V": 0, "3-25 bridge": 1, "3-25 R": 2, "Accio": 1, "Avada Kedavra": 3, "Invalid": 4, "Lumos": 0, "Revelio": 2}

vid_class = {} # name in processed_vid : category


for root, dirs, files in os.walk(source_dir):
    tmp_root = root[root.rfind('/') + 1: ]
    tmp_root = tmp_root[tmp_root.rfind('\\') + 1: ]
    category = None if tmp_root not in category_mapping.keys() else category_mapping[tmp_root]
    for name in files:
        if not name.endswith('mp4'):
            continue
        assert category is not None, f"No label at{os.path.join(root, name)} {tmp_root}"

        vid_class[name] = category

In [7]:
vid_class.keys()

dict_keys(['IMG_6458.mp4', 'IMG_6459_8.mp4', 'IMG_6458_2.mp4', 'IMG_6458_4.mp4', 'IMG_6458_6.mp4', 'IMG_6458_7.mp4', 'IMG_6458_5.mp4', 'IMG_6458_9.mp4', 'IMG_6458_8.mp4', 'IMG_6458_3.mp4', 'IMG_6458_11.mp4', 'IMG_6458_10.mp4', 'IMG_6458_12.mp4', 'IMG_6458_14.mp4', 'IMG_6458_13.mp4', 'IMG_6458_15.mp4', 'IMG_6458_16.mp4', 'IMG_6458_18.mp4', 'IMG_6458_19.mp4', 'IMG_6458_17.mp4', 'IMG_6459.mp4', 'IMG_6459_2.mp4', 'IMG_6459_3.mp4', 'IMG_6459_4.mp4', 'IMG_6459_5.mp4', 'IMG_6459_6.mp4', 'IMG_6459_7.mp4', 'IMG_6459_9.mp4', 'IMG_6459_10.mp4', 'IMG_6459_11.mp4', 'IMG_6460_9.mp4', 'IMG_6460_10.mp4', 'IMG_6460_11.mp4', 'IMG_6460_12.mp4', 'IMG_6460_13.mp4', 'IMG_6460_14.mp4', 'IMG_6460_15.mp4', 'IMG_6460_16.mp4', 'IMG_6460_17.mp4', 'IMG_6460_18.mp4', 'IMG_6460_19.mp4', 'IMG_6460_20.mp4', 'IMG_6460_21.mp4', 'IMG_6460_22.mp4', 'IMG_6460_23.mp4', 'IMG_6460_24.mp4', 'IMG_6460_25.mp4', 'IMG_6460_26.mp4', 'IMG_6460.mp4', 'IMG_6460_2.mp4', 'IMG_6460_3.mp4', 'IMG_6460_4.mp4', 'IMG_6460_5.mp4', 'IMG_6460_6.

In [8]:

def pad_seq(j, pad_length = 90, device = device):
    res = torch.zeros(size=(pad_length, j.shape[1]), dtype=torch.long)
    padded = pad_length - j.shape[0]
    res[int(padded / 2): int(padded / 2) + j.shape[0],:] = j
    return res.to(device)


# keypoints_mapping_padded = {}
dataset = []

for file_name, j in keypoints_mapping.items():
    file_name = file_name[file_name.find('-') + 1:]
    dataset.append((pad_seq(j), torch.tensor(vid_class[file_name], dtype = torch.long, device = device)))
    # print(j.shape, vid_class[file_name])

import random

random.shuffle(dataset)
d = int(len(dataset) * 0.85)


train = dataset[:d]
val = dataset[d:]

In [9]:
model_name = "./runs/detect/train5/weights/best.pt"

keypoints_pred_mapping = {}

for i in all_tasks:
    file_name = i['data']['video']
    file_name = file_name[file_name.rfind('/') + 1:]
    preds = i['predictions']
    for j in preds[::-1]:
        if j['model_version'] == model_name:
            framesCount, wand_end_keypoint, wand_tip_keypoint = process_seq(j['result'])
            concat_keypoint = np.zeros(shape=(framesCount, 2))
            concat_keypoint[:, :1] = wand_end_keypoint
            concat_keypoint[:, 1:] = wand_tip_keypoint

            keypoints_pred_mapping[file_name] = torch.tensor(concat_keypoint, dtype=torch.long)
            break

In [10]:
dataset_pred = []
missing = 0


for file_name, j in keypoints_pred_mapping.items():
    file_name = file_name[file_name.find('-') + 1:]
    if file_name in vid_class.keys():
        dataset_pred.append((pad_seq(j), torch.tensor(vid_class[file_name], dtype = torch.long, device=device)))
    # else:
    #     missing += 1
    #     print(file_name)
    # print(j.shape, vid_class[file_name])

import random

random.shuffle(dataset_pred)
d = int(len(dataset_pred) * 0.85)


train_pred = dataset_pred[:d]
val_pred = dataset_pred[d:]

In [11]:
from torch.utils.data import Dataset

class ClsDataset(Dataset):
    """Face Landmarks dataset."""

    def __init__(self, data):
        """
        Arguments:
            csv_file (string): Path to the csv file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):

        return self.data[idx]
    
train_dataset = ClsDataset(train_pred)
val_dataset = ClsDataset(val_pred)

In [12]:
from torch.utils.data import DataLoader
batch_size = 16

train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

In [26]:
import torch
from torch import nn

class lstm(nn.Module):
    def __init__(self, embed_size = 30, num_layers = 2):
        super(lstm, self).__init__()
        
        self.embedding = nn.Embedding(x_grid_size * y_grid_size + 1, embed_size)
        self.rnn1 = nn.LSTM(input_size = embed_size, hidden_size = 100, batch_first = True, bidirectional = True, dropout = 0.1, num_layers = num_layers)
        self.rnn2 = nn.LSTM(input_size = embed_size, hidden_size = 100, batch_first = True, bidirectional = True, dropout = 0.1, num_layers = num_layers)
        self.dropout = nn.Dropout(p = 0.1)
        self.relu = nn.LeakyReLU()
        self.fc1 = nn.Linear(400, 200)
        self.fc2 = nn.Linear(200, 5)

    def forward(self, x):
        # print(self.rnn(x)[1][0].shape)
        # return self.fc(torch.squeeze(self.rnn(x)[1][0], dim=0))
        # print(self.rnn(x)[0].shape)
        return self.fc2(self.relu( \
            self.fc1(self.dropout(torch.cat((self.rnn1(self.embedding(x[:, :, 0]))[0][:, -1, :], self.rnn2(self.embedding(x[:, :, 1]))[0][:, -1, :]), dim=-1)))))


def get_grouped_params(model, weight_decay, no_decay=["bias", "rnn"]):
    params_with_wd, params_without_wd = [], []
    for n, p in model.named_parameters():
        if any(nd in n for nd in no_decay):
            params_without_wd.append(p)
        else:
            params_with_wd.append(p)
    return [
        {"params": params_with_wd, "weight_decay": weight_decay},
        {"params": params_without_wd, "weight_decay": 0.0},
    ]

In [14]:
# torch.cat((torch.zeros(size=(1,100)), torch.zeros(size=(1,100))), dim = 1).shape

In [27]:
from torch.optim import Adam

model = lstm().to(device)
optimizer = Adam(get_grouped_params(model, 0.1), lr = 1e-4)

In [16]:
cnts = [0] * 5
for feature, label in train:
    cnts[label.item()] += 1
cnts

[48, 19, 30, 11, 1]

In [17]:
cnts = [0] * 5
for feature, label in val:
    cnts[label.item()] += 1
cnts

[6, 6, 6, 2, 0]

In [30]:
n_epochs = 100
from torch.nn import CrossEntropyLoss


crossEntropy = CrossEntropyLoss()

for i in range(n_epochs):
    # train_feature_w2v, train_label_w2v = shuffle(train_feature_w2v, train_label_w2v)
    model.train()
    loss_list = []
    correct = 0
    all = 0
    # random.shuffle(train_pred)
    for feature, label in train_dataloader:
        # print(feature.shape)
        output = model(feature)
        loss = crossEntropy(output.view((-1, 5)), label.view((-1,)))
        correct += torch.sum(torch.argmax(output, dim = 1) == label).item()
        all += feature.shape[0]

        optimizer.zero_grad()
        loss.backward()
        loss_list.append(loss.item())
        optimizer.step()
    train_acc = correct / all
    correct = 0
    all = 0
    model.eval()
    for feature, label in val_dataloader:
        all += feature.shape[0]
        output = model(feature)
        # print(torch.argmax(output, dim = 1), label)
        correct += torch.sum(torch.argmax(output, dim = 1) == label).item()

    print("val acc: ",correct / all, "train loss: ", np.mean(loss_list), "train acc:", train_acc)

val acc:  0.5172413793103449 train loss:  0.26009746037778403 train acc: 0.9507692307692308
val acc:  0.5 train loss:  0.2616824238073258 train acc: 0.9507692307692308
val acc:  0.4827586206896552 train loss:  0.25179934359732126 train acc: 0.9538461538461539
val acc:  0.5172413793103449 train loss:  0.25324368689741406 train acc: 0.9569230769230769
val acc:  0.5 train loss:  0.2561209652395475 train acc: 0.96
val acc:  0.5689655172413793 train loss:  0.27246719421375365 train acc: 0.9415384615384615
val acc:  0.5 train loss:  0.27491606984819683 train acc: 0.9415384615384615
val acc:  0.5689655172413793 train loss:  0.26415610987515675 train acc: 0.9476923076923077
val acc:  0.5862068965517241 train loss:  0.24805322786172232 train acc: 0.96
val acc:  0.5172413793103449 train loss:  0.2519179696128482 train acc: 0.9476923076923077
val acc:  0.5172413793103449 train loss:  0.24409754893609456 train acc: 0.9661538461538461
val acc:  0.5344827586206896 train loss:  0.25641526707581114 tr

In [22]:
label

tensor([0, 0, 1, 3], device='cuda:0')

In [21]:
torch.argmax(output, dim = 1)

tensor([0, 0, 0, 3], device='cuda:0')

In [31]:
dataset_pred_flattened = []
dataset_pred_label = []

dataset_pred_flattened_val = []
dataset_pred_label_val = []

for i, j in train_pred:
    dataset_pred_flattened.append(i.view((-1,)).cpu().numpy())
    dataset_pred_label.append(j.item())


for i, j in val_pred:
    dataset_pred_flattened_val.append(i.view((-1,)).cpu().numpy())
    dataset_pred_label_val.append(j.item())

In [42]:
from sklearn.linear_model import Perceptron, SGDClassifier
from sklearn.metrics import accuracy_score


clf_perceptron = SGDClassifier(max_iter=1000)
clf_perceptron.fit(dataset_pred_flattened, dataset_pred_label)

accuracy_score(dataset_pred_label_val, clf_perceptron.predict(dataset_pred_flattened_val))

0.3793103448275862

In [20]:
# torch.argmax(output, dim = 1)

In [21]:
# torch.argmax(output, dim = 1) == torch.tensor([2])

In [22]:
label

tensor([3], device='cuda:0')

In [23]:
from sklearn.metrics import accuracy_score

from sklearn.linear_model import Perceptron

clf_perceptron = Perceptron()
clf_perceptron.fit(train_feature, train_label)

accuracy_score(test_label, clf_perceptron.predict(test_feature))

NameError: name 'train_feature' is not defined